import {
  PROJECT_CONTENT,
  ADDONS_CONTENT,
  TIMING_CONTENT,
  FILES_AND_PROGRAMS_CONTENT,
  PRICING_AND_CANCELATION_POLICY_CONTENT,
  WHITE_SPACE_RENOVATION_CONTENT,
} from './side-card-fqa.content';

export enum FQALabels {
  PROJECT = 'PROJECTS',
  ADDONS = 'ADD-ONS',
  TIMING = 'TIMING',
  FILES_AND_PROGRAMS = 'FILES AND PROGRAMS',
  PRICING_AND_CANCELATION_POLICY = 'PRICING AND CANCELATION POLICY',
  WHITE_SPACE_RENOVATION = 'WHITE SPACE RENOVATION',
}

export const FQAContentObj = {
  PROJECTS: PROJECT_CONTENT,
  'ADD-ONS': ADDONS_CONTENT,
  TIMING: TIMING_CONTENT,
  'FILES AND PROGRAMS': FILES_AND_PROGRAMS_CONTENT,
  'PRICING AND CANCELATION POLICY': PRICING_AND_CANCELATION_POLICY_CONTENT,
  'WHITE SPACE RENOVATION': WHITE_SPACE_RENOVATION_CONTENT,
};
